### ISSUE TITLE
Suggestion: display in the form rather than in the sidebar

### ISSUE THREAD

**Issue by Thiousi** [jenstornell/kirby-headline-jump#1]
Great idea Jens, I love it!

Can I suggest that this be optionally displayed in the form rather than in the sidebar?

Maybe with an option:

```
display: sidebar
display: inline
```

**Comment by jenstornell** [comment]
Thanks! I had it in the form from the beginning but I thought it took too much space with many headlines.

Another thing is that the sidebar is fixed so the links to the headlines are always reachable. When using it in the form, the links to the headlines are on top and disapear on scroll (on longer forms).

Is there any special reason why you prefer them to be in the form?

**Comment by Thiousi** [comment]
Yes, for a one pager that doesn't have the sidebar. But I guess that's not
a really good reason!

**Comment by jenstornell** [comment]
Ahh, I see. Let's say you have it in your form and click "Headline 2" and it jumps down. Then you want to jump to "Headline 5", how do you do that? Scroll all the way up and then click to scroll all the way down to "Headline 5"?

That was the reason why I moved it. I did not get any workflow out of that.

**Comment by Thiousi** [comment]
It's definitely not as easy to use as having it in the sidebar surely!

**Comment by jenstornell** [comment]
I'll keep it open. Maybe in a future version. not sure yet.

**Comment by jenstornell** [comment]
Will not change this
