### ISSUE TITLE
layout broken for site.yml

### ISSUE THREAD

**Issue by bnomei** [jenstornell/kirby-headline-jump#4]
when using headline-jump on site.yml a `div.section` wrapper is needed.

**Comment by jenstornell** [comment]
I've actually never tested it on the panel site option page, but it seems to be a good find. Thanks for reporting.

**Comment by jenstornell** [comment]
While I was working on the plugin, I fixed this issue as well. It's strange that the sidebars are using different elements like this. Anyway, should be working fine now. Closing this.
